src/website/models.py
from website import db
import flask
from flask_login import UserMixin
from werkzeug.security import generate_password_hash

#model for users
class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(70), unique=True)
    password = db.Column(db.String(70))
    priv = db.Column(db.String(70))

#model for contract employee table
class Contract_employees(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    firstname = db.Column(db.String(100), nullable=False)
    lastname = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(80), unique=True, nullable=False)
    address = db.Column(db.Text)
    joined = db.Column(db.String(80), nullable=False)
    role = db.Column(db.Text, nullable=False)

#model for non-contract employee table
class Non_contract_employees(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    firstname = db.Column(db.String(100), nullable=False)
    lastname = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(80), unique=True, nullable=False)
    contact = db.Column(db.Text)
    role = db.Column(db.Text, nullable=False)



    

src/website/__init__.py
from flask import Flask 
from flask_sqlalchemy import SQLAlchemy
import os
from os import path
from flask_login import LoginManager



db=SQLAlchemy()
DB="database.db"


def create_app(sql_path):
    
    app = Flask(__name__)

    #secure session data: encrypt the session data and cookies related to our website
    app.config['SECRET_KEY'] = 'Cisco123!'
    app.config['SQLALCHEMY_DATABASE_URI'] = sql_path
    db.init_app(app)

    from .views import views
    from .models import Contract_employees, Non_contract_employees, User
    from .authentication import auth

    
    create_database(app)



    login_manager = LoginManager()
    login_manager.init_app(app)
    login_manager.login_view = 'authentication.login'

    @login_manager.user_loader
    def load_user(id):
            return User.query.get(int(id))
    
    

    app.config['SECRET_KEY'] = 'mysecret'

    #register views
    app.register_blueprint(views, url_prefix='/')

    app.register_blueprint(auth, url_prefix='/')

    return app

#function to check if db already exists. If not then db is created

def create_database(app):
    if not path.exists('website/' + DB):
        with app.app_context():
            db.create_all()

        

src/website/views.py
#this file stores standard roots for our website

from flask import Blueprint,render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from website.models import Contract_employees, Non_contract_employees, User
from website import db



#define the file as blueprint of the application 
views = Blueprint('views',__name__)

@views.route('/')
@login_required
def home():
    contract_employee=Contract_employees.query.all()
    non_contract_employee=Non_contract_employees.query.all()
    return render_template("home.html", new_user=current_user,no_contract_info=non_contract_employee,employees_info=contract_employee, priv=current_user.priv),200

#Add a new contract employee
@views.route("/new_contract_employee",methods=['POST','GET'])
@login_required
def new_contract_employee():
    if request.method=='POST':
        firstname=request.form.get('firstname')
        lastname=request.form.get('lastname')
        email=request.form.get('email')
        address=request.form.get('address')
        joined=request.form.get('joined')
        role=request.form.get('role')
        employee=Contract_employees(firstname=firstname,
                                lastname=lastname, 
                                email=email, 
                                address=address, 
                                joined=joined, 
                                role=role)
        
        db.session.add(employee)
        db.session.commit()
        flash('Employee has been added')
        return redirect(url_for("views.home"))
    return render_template("new_contract_employee.html",new_user=current_user)

@views.route("/new_no_contract_employee",methods=['POST','GET'])
@login_required
def new_no_contract_employee():
    if request.method=='POST':
        firstname=request.form['firstname']
        lastname=request.form['lastname']
        email=request.form['email']
        contact=request.form['contact']
        role=request.form['role']
        employee=Non_contract_employees(firstname=firstname,
                                    lastname=lastname, 
                                    email=email, 
                                    contact=contact, 
                                    role=role)
        db.session.add(employee)
        db.session.commit()
        flash('No contract employee has been added')
        return redirect(url_for("views.home"))
    return render_template("new_no_contract_employee.html", new_user=current_user)

@views.route("/edit_employee/<string:id>",methods=['POST','GET'])
@login_required
def edit_employee(id):
    employee=Contract_employees.query.get_or_404(id)
    if request.method=='POST':
        employee.firstname=request.form.get('Firstname')
        employee.lastname=request.form.get('Lastname')
        employee.email=request.form.get('Email')
        employee.address=request.form.get('Address')
        employee.joined=request.form.get('Joined')
        employee.role=request.form.get('Role')
        db.session.add(employee)
        db.session.commit()
        flash('Employee has been updated')
        return redirect(url_for("views.home"))
    return render_template("edit_employee.html",employees_info=employee, new_user=current_user)

#Edit non-contract employee
@views.route("/edit_no_contract_employee/<string:id>",methods=['POST','GET'])
@login_required
def edit_no_contract_employee(id):
    employee=Non_contract_employees.query.get_or_404(id)
    if request.method=='POST':
        employee.firstname=request.form.get('Firstname')
        employee.lastname=request.form.get('Lastname')
        employee.email=request.form.get('Email')
        employee.contact=request.form.get('Contact')
        employee.role=request.form.get('Role')
        db.session.commit()
        flash('No contract employee has been updated')
        return redirect(url_for("views.home"))
    return render_template("edit_no_contract_employee.html",no_contract_info=employee, new_user=current_user)


#Delete a contract emoployee   
@views.route("/delete_employee/<int:id>",methods=['GET','POST'])
@login_required
def delete_employee(id):
    if current_user.priv=="1":
        flash('You are not permitted to execute this action')
        return redirect(url_for("views.home", new_user=current_user))
    else:
        employee=Contract_employees.query.get_or_404(id)
        db.session.delete(employee)
        db.session.commit()
        flash('Employee deleted')
        return redirect(url_for("views.home", new_user=current_user))
    

#Delete a non-contract emoployee 
@views.route("/delete_no_contract_employee/<int:id>",methods=['GET','POST'])
@login_required
def delete_no_contract_employee(id):
    if current_user.priv=="1":
        flash('You are not permitted to execute this action')
        return redirect(url_for("views.home", new_user=current_user))
    else:
        employee=Non_contract_employees.query.get(id)
        db.session.delete(employee)
        db.session.commit()
        flash('Non-contract employee deleted')
        return redirect(url_for("views.home", new_user=current_user))

src/website/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, intial-scale=1">
        
        <title>{% block title %}Title{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    </head>
    <body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            {% if new_user.is_authenticated %}
            <li class="nav-item active">
              <a class="nav-link" href="{{ url_for('views.home')}}">Home</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{{ url_for('authentication.logout')}}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('authentication.login') }}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('authentication.registration')}}">Register</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>

      {% with messages = get_flashed_messages(with_categories=true) %} {% if
        messages %} {% for category, message in messages %} {% if category ==
        'error' %}
        <div class="alert alert-danger alter-dismissable fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-bs-dismiss="alert" onclick=delete_flash(this)>
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% else %}
        <div class="alert alert-success alter-dismissable fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-bs-dismiss="alert" onclick=delete_flash(this)>
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endif %} {% endfor %} {% endif %} {% endwith %}

    
      
    <div class="container">
    {% block content%}{% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </body>
</html>

src/website/templates/edit_employee.html
{% extends 'base.html' %}
{% block title %}Edit employee information{% endblock %}

{% block content %}
    <div class='row'>
        <h3>Edit employee information</h3><hr>
        <form method='post' action='{{url_for("views.edit_employee",id=employees_info.id)}}'>
            <p>
                <label for="Firstname">Firstname</label>
                <input type="text" name="Firstname" required class='form-control' value='{{employees_info.Firstname}}'>
                </input>
            </p>
                
            <p>
                <label for="Lastname">Lastname</label>
                <input type="text" name="Lastname" required class='form-control' value='{{employees_info.Lastname}}'>
                </input>
            </p>
            <p>
                <label for="Email">Email</label>
                <input type="text" name="Email" required class='form-control' value='{{employees_info.Email}}'>
                </input>
            </p>

            <p>
                <label for="Address">Address</label>
                <input type="text" name="Address" required class='form-control' value='{{employees_info.Address}}'>
                </input>
            </p>

            <p>
                <label for="Joined">Joined</label>
                <input type="text" name="Joined" required class='form-control' value='{{employees_info.Joined}}'>
                </input>
            </p>

            <p>
                <label for="Role">Role</label>
                <input type="text" name="Role" required class='form-control' value='{{employees_info.Role}}'>
                </input>
            </p>

            <input type='submit' value='Submit' class='btn btn-primary'>
        </form>
        
    </div>

{% endblock %}

src/website/templates/edit_no_contract_employee.html
{% extends 'base.html' %}
{% block title %}>Edit No contract employee information{% endblock %}

{% block content %}
    <div class='row'>
        <h3>Edit no contract employee information</h3><hr>
        <form method='post' action='{{url_for("views.edit_no_contract_employee",id=no_contract_info.id)}}'>
            <p>
                <label for="Firstname">Firstname</label>
                <input type="text" name="Firstname" required class='form-control' value='{{no_contract_info.Firstname}}'>
                </input>
            </p>
                
            <p>
                <label for="Lastname">Lastname</label>
                <input type="text" name="Lastname" required class='form-control' value='{{no_contract_info.Lastname}}'>
                </input>
            </p>
            <p>
                <label for="Email">Email</label>
                <input type="text" name="Email" required class='form-control' value='{{no_contract_info.Email}}'>
                </input>
            </p>

            <p>
                <label for="Contact">Contact</label>
                <input type="integer" name="Contact" required class='form-control' value='{{no_contract_info.Contact}}'>
                </input>
            </p>

            <p>
                <label for="Role">Role</label>
                <input type="text" name="Role" required class='form-control' value='{{no_contract_info.Role}}'>
                </input>
            </p>

            <input type='submit' value='Submit' class='btn btn-primary'>
        </form>
        
    </div>

{% endblock %}

src/website/templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}

{% block content%}

<h1>Home</h1>

<div class="pt-3">
    <h3>Contract employees</h3>
    <a class="btn btn-outline-primary" class="link-secondary" href='{{url_for("views.new_contract_employee")}}' >Add employee</a>

    <table class="table table-striped">
        <thead> 
            <tr>
                <th scope="col">#</th>
                <th scope="col">Firstname</th>
                <th scope="col">Lastname</th>
                <th scope="col">Email</th>
                <th scope="col">Address</th>
                <th scope="col">Joined</th>
                <th scope="col">Role</th>
                <th scope="col">Edit</th>
                <th scope="col">Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for employee in employees_info %}
            <tr>
                <th score="row">{{loop.index}}</th>
                <td>{{employee.firstname}}</td>
                <td>{{employee.lastname}}</td>
                <td>{{employee.email}}</td>
                <td>{{employee.address}}</td>
                <td>{{employee.joined}}</td>
                <td>{{employee.role}}</td>
                <td><a href='{{url_for("views.edit_employee",id=employee.id)}}' class='btn-edit'>Edit</a></td>
                <td><a href='{{url_for("views.delete_employee",id=employee.id)}}' class='btn-delete' onclick='return confirm("Are you sure you want to delete")'>Delete</a></td>
            </tr>
            {%endfor%}
        </tbody>
    </table>
</div>

<div class="pt-3">
    <h3>Non-contract employees</h3>
    <a class="btn btn-outline-primary" href='{{url_for("views.new_no_contract_employee")}}'>Add non-contract employee</a>

    <table class="table table-striped"> 
        <thead>
            <th>#</th>
            <th>Firstname</th>
            <th>Lastname</th>
            <th>Email</th>
            <th>Contact</th>
            <th>Role</th>
            <th>Edit</th>
            <th>Delete</th>
        </thead>
        <tbody>
            {% for employee in no_contract_info %}
            <tr>
                <th scope="row">{{loop.index}}</th>
                <td>{{employee.firstname}}</td>
                <td>{{employee.lastname}}</td>
                <td>{{employee.email}}</td>
                <td>{{employee.contact}}</td>
                <td>{{employee.role}}</td>
                <td><a href='{{url_for("views.edit_no_contract_employee",id=employee.id)}}' class='btn-edit'>Edit</a></td>
                <td><a href='{{url_for("views.delete_no_contract_employee",id=employee.id)}}' class='btn-delete' onclick='return confirm("Are you sure you want to delete")'>Delete</a></td>
            </tr>
            {%endfor%}
        </tbody>
    </table>
</div>       






{% endblock content %}

src/website/templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content%}
    
    <h1>Login</h1>

        <form method="post">
            <div class="container">
                <p>
                    <label for="email">Email</label>
                    <input type="email" name="email" class='form-control' id='email'></input>
                </p>
                <p>
    
                    <label for="password">Password</label>
                    <input type="password" name="password" class='form-control' id='password'></input>
    
                </p>

                <p>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </p>
            </div>
        </form>
    

{% endblock %}

src/website/templates/new_contract_employee.html
{% extends 'base.html' %}
{% block title %}Add Contract Employee{% endblock %}
{% block content %}
    <div class='row'>
        <h3>Add new employee</h3><hr>
        <form method='post' action='{{url_for("views.new_contract_employee")}}'>
            <p>
                <label for="firstname">Firstname</label>
                <input type="text" name="firstname" 
                required class='form-control'>
                </input>
            </p>

            <p>
                <label for="lastname">Lastname</label>
                <input type="text" name="lastname"
                required class='form-control'>
                </input>
            </p>

            <p>
                <label for="email">Email</label>
                <input type="email" name="email"
                required class='form-control'>
                </input>
            </p>

            <p>
                <label for="address">Address</label>
                <input type="text" name="address"
                required class='form-control'>
                </input>
            </p>

            <p>
                <label for="joined">Date joined</label>
                <input type="text" name="joined"
                required class='form-control'>
                </input>
            </p>

            <p>
                <label for="role">Role</label>
                <input type="=text" name="role"
                required class='form-control'>
                </input>
            </p>
            <input type='submit' value='Submit' class='btn btn-primary'>
        </form>
        
    </div>
{% endblock %}

src/website/templates/new_no_contract_employee.html
{% extends 'base.html' %}
{% block title %}Add No Contract Employee{% endblock %}
{% block content %}
    <div class='row'>
        <h3>Add new non contract employee</h3><hr>
        <form method='post' action='{{url_for("views.new_no_contract_employee")}}'>
            <p>
                <label for="firstname">Firstname</label>
                <input type="text" name="firstname"
                required class='form-control'>
                </input>
            </p>

            <p>
                <label for="lastname">Lastname</label>
                <input type="text" name="lastname"
                required class='form-control'>
                </input>
            </p>

            <p>
                <label for="email">Email</label>
                <input type="email" name="email"
                required class='form-control'>
                </input>
            </p>

            <p>
                <label for="contact">Contact</label>
                <input type="integer" name="contact"
                required class='form-control'>
                </input>
    
            </p>

            <p>
                <label for="role">Role</label>
                <input type="=text" name="role"
                required class='form-control'>
                </input>
            </p>
            <input type='submit' value='Submit' class='btn btn-primary'>
        </form>
        
    </div>
{% endblock %}

src/website/templates/registration.html
{% extends 'base.html' %}
{% block title %}Register{% endblock %}

{% block content %}
<h1>Register</h1>
    <form method="POST">
        <div class="container">
            <p>
  
                <label for="email">Email</label>
                <input type="email" name="email" class='form-control' id='email' placeholder="Your Email"></input>
                <div class="input-group-append">
                    <span class="input-group-text">@example.com</span>
                  </div>

            </p>
            <p>
                <label for="password">Password</label>
                <input type="password" name="password" class='form-control' id='password' placeholder="Password"></input>
            </p>
            <p>
                <label for="password1">Password</label>
                <input type="password" name="password1" class='form-control' id='password1' placeholder="Confirm password"></input>
            </p>
            <input type="submit" class="btn btn-primary" value="Submit"/>
        </div>
    </form>
{% endblock %}